### ISSUE TITLE
manually engaging help screen?

### ISSUE THREAD

**Issue by lonnietc** [bsonnino/CommandLine#1]
Hello,

I am working on a project in which there will be an executable and then there may, or may not, be a file but could be some additional command line options.

For example in Microsoft Excel you might have a workbook.xls specified or you may not but could still have some command line switches.  My project is similar.

```
program.exe [<path\workkbook.xls>]  --verbose --workingPath C:\tmp  
```

So far, I have found that your FileInfoParams and ShowFileContents example exhibit some "similar" properties but not exact.

What I need is to determine the Path & File if they are present in which case I pass them to another function, but if they are not present then I do not want the Help menu to come up but instead I need to check if some Plugins are loaded first. The the Plugins are loaded then I execute a function, but if the Plugin is not loaded then I activate the Help menu that you would normally see.

Can you please assist me in getting one of your examples to be able to read the file name, if present, but if not then just do a simple function or manually call the Help menu?

Any information that you could provide would be greatly appreciated.
Thanks

**Comment by bsonnino** [comment]
From what I understand, you need something like this:

```csharp
var command = new RootCommand
            {
                new Argument("workbook","Workbook Name"),
                new Option(new [] {"--verbose", "-v"}),
                new Option("--workingPath") { Argument = new Argument<string>() }
            };

            command.Handler = CommandHandler.Create(
                (string workBook, bool verbose, string workingPath) =>
                {
                    if (workBook != null && FileExists(workBook)  && workingPath != null && Directory.Exists(workingPath))
                    {
                        if (verbose)
                            Console.WriteLine($"Some Verbose Comment");

                        // Process files;
                    }
                    else
                    {
                        if (verbose)
                            Console.WriteLine("No file or path");
                    }
                });
            await command.InvokeAsync(args);
```

**Comment by lonnietc** [comment]
@bsonnino Hello and thanks for getting back to me.

Please forgive me as I am still a bit new to C# but am coming from a C/C++ and other languages background.

I am trying to follow the code and it teems that typical inputs could be, for example:

``` 
(Just some examples)

//  CASE 1: with no filename or path
C:\user> demo.exe 

// CASE 2: with command line switches and workbook (Path and workbook.xls separated)
C:\user> demo.exe  --workingPath C:\temp  --verbose workbook.xls

// CASE 3: with just filename with path, or just application with workbook.xls
C:\user> demo.exe  C:\temp\workbook.xls

// CASE 4: with just switches and no filename
C:\user> demo.exe --workingPath C:\temp --verbose

// CASE 5:  show help menu which would call the CommandLine method to show the help screen (or similar)
C:\user>  demo.exe --help   (or ? perhaps)
```

I am thinking that the code you showed could do most of this and I am going to give it a try.
Thanks again, my friend.

**Comment by bsonnino** [comment]
Yes, it covers all cases (except 3 and 4), but a new condition could cover them

**Comment by lonnietc** [comment]
Actually, those are the most important cases.

What kind of condition would need to be added?
Thanks for your help as it is truly appreciated.

**Comment by lonnietc** [comment]
Hello @bsonnino 

What version of System.CommandLine are you using?

I have to use 2.0.0-beta1.20158.1 for the previous examples that are in the Repo, which compiled just fine for those, but when I try to apply the code that you supplied in this thread, with that installed CommandLine version then I get an error:

```
Severity	Code	Description
Error	CS1729	'Argument' does not contain a constructor that takes 2 arguments
```

However, if I upgrade to the latest System.CommandLine version then that error goes away, but others show up.

Any ideas on a solution would be greatly appreciated.

**Comment by bsonnino** [comment]
For the cases, it should be something like 

```
if (workBook != null && FileExists(workBook))
{
  // Process workbook
}
....
```

For the error, it may be that Argument has changed and you need to create it with different parameters. You should check the docs and see what's changed.

**Comment by lonnietc** [comment]
Thanks again,

I'll dig into it more to see if I can get things working.
